---
title: "warmup"
author: "Amanda Duong"
date: "2024-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Warm-up
### 1. Build a vector that includes the following height measurements for five plants: plant 1 30.7, plant 2 37.6, plant 3 28.4, plant 4 NA, plant 5 33.2
```{r}
height <- c(30.7, 37.6, 28.4, NA, 33.2)
```

### 2. Build another vector that includes the following mass measurements:
plant 1 4, plant 2 5.2, plant 3 3.7, plant 4 NA, plant 5 4.6
```{r}
mass <- c(4, 5.2, 3.7, NA, 4.6)
```

### 3. Assemble these vectors into a labeled data matrix with two columns
```{r}
samples <- c("Plant 1", "Plant 2", "Plant 3", "Plant 4", "Plant 5")
measurements <- c("Height", "Mass")
```
```{r}
plant <- c(height, mass)
plant_matrix <- matrix(plant, nrow = 5, byrow = F)
colnames(plant_matrix) <- measurements
rownames(plant_matrix) <- samples
```

### 4. Calculate the mean for height and mass and add them to the data matrix
```{r}
Means <- colMeans(plant_matrix, na.rm = T)
new_plant_matrix <- rbind(plant_matrix, Means)
new_plant_matrix
```

